# Default Configuration for LiDM (Lightweight Display Manager)
# All settings shown below with their default values.

[colors.bg]
bg = "#261c1c"
modifiers = []

[colors.fg]
color = "#f5f5f5"
modifiers = []

[colors.err]
color = "red"
modifiers = ["bold"]

[colors.warn]
color = "yellow"
modifiers = []

[colors.s_wayland]
color = "#ffae42"
modifiers = []

[colors.s_xorg]
color = "#25afff"
modifiers = []

[colors.s_shell]
color = "green"
modifiers = []

[colors.e_hostname]
color = "lightred"
modifiers = []

[colors.e_date]
color = "darkgray"
modifiers = []

[colors.e_box]
color = "gray"
modifiers = []

[colors.e_header]
color = "green"
modifiers = ["underlined"]

[colors.e_user]
color = "cyan"
modifiers = []

[colors.e_passwd]
color = "#f5f5cd"
modifiers = ["underlined"]

[colors.e_badpasswd]
color = "red"
modifiers = [
    "italic",
    "underlined",
]

[colors.e_key]
color = "#ffae42"
modifiers = []

[chars]
hb = "─"
vb = "│"
ctl = "┌"
ctr = "┐"
cbl = "└"
cbr = "┘"

[functions]
poweroff = "F1"
reboot = "F2"
refresh = "F5"
theme = "F3"

[strings]
f_poweroff = "poweroff"
f_reboot = "reboot"
f_refresh = "refresh"
f_fido = "fido"
f_theme = "theme"
e_user = "user"
e_passwd = "password"
s_wayland = "wayland"
s_xorg = "xorg"
s_shell = "shell"
opts_pre = "< "
opts_post = " >"
ellipsis = "…"

[behavior]
box_type = "border"
include_defshell = true
show_console = false
source = []
user_source = []
timefmt = "%Y-%m-%d %H:%M:%S"
refresh_rate = 100
bypass_shell_login = false

[logging]
file = "/tmp/lidm.log"
level = "debug"
stdout = false

[auth]
pam_service = "login"
