name: Check

on:
  workflow_call:

jobs:
  spellcheck:
    name: Grammar
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: "codespell"
          version: 1.0
      - run: codespell

  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: "shellcheck"
          version: 1.0
      - run: git ls-files "*.sh" "*/PKGBUILD" | xargs shellcheck --shell=bash

  clippy:
    name: Clippy & Format
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - run: cargo fmt --check
      - run: cargo clippy -- -D warnings
