name: _

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: Check
    uses: ./.github/workflows/check.yml
    permissions: write-all
  check_paths:
    name: Paths Filter
    runs-on: ubuntu-latest
    outputs:
      code_changed: ${{ steps.filter.outputs.code }}
    steps:
      - uses: actions/checkout@v7
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            code:
              - Makefile
              - 'src/**'
              - Cargo.toml
              - Cargo.lock
# Disabled temporarily until multi-architecture Rust release build workflow is resolved in a separate issue.
#  build:
#    name: Build
#    needs: check_paths
#    if: github.event_name != 'push' || needs.check_paths.outputs.code_changed == 'true'
#    uses: ./.github/workflows/build.yml
#    permissions: write-all
